UpdateZoneUserStatus:
   MasterData_UpdateZoneUserStatus_All_Valid_Smoke_sid:  
      endPoint: /v1/masterdata/zoneuser?isActive={isActive}&userId={userId}
      role: admin
      restMethod: patch
      inputTemplate: ivv_masterdata/UpdateZoneUserStatus/updateZoneUserStatus
      outputTemplate: ivv_masterdata/UpdateZoneUserStatus/updateZoneUserStatusResult
      input: '{
    "userId": "func_auto_test_user",
    "isActive": "true"
}'
      output: '{
    "status": "Status updated successfully for Zone"
}'