GetMachines:
   Admin_GetMachines_allValid_smoke:
      endPoint: /v1/syncdata/configs/change
      role: admin
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: syncdata/configkeyindex/getConfigKeyIndex
      outputTemplate: syncdata/configkeyindex/getConfigKeyIndexResult
      input: '{
     }'
      output: '{
    }'  